[agent]
    hostname = "Data_Mapper"
[[inputs.mqtt_consumer]]
    servers: ["tcp://broker:1883"]
    topics = ["sensor/+"]
    data_format = "value"
    data_type = "integer"
    topic_tag = "source"

[[outputs.influxdb_v2]]
    urls = ["http://influxdb:8086"]
    token = "3TJprljLmJ9ZaWSA"
    ogranization = "iot"
    bucket = "sensor_data"