apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: iot-monitoring
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: iot-project
  DOCKER_INFLUXDB_INIT_ORG: iot-org
  DOCKER_INFLUXDB_INIT_BUCKET: sensors
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 3TJprljLmJ9ZaWSA