apiVersion: apps/v1
kind: Deploymenet
metadata:
  name: mosquitto
  namespace: iot-monitoring
spec:
  replica: 1
  selector:
    matchLabels: {app: mosquitto}
  template:
    metadata:
      labels: {app: mosquitto}
    spec:
      containers:
        - name: broker
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources:
            requests: {cpu: 50m, memory: 32Mi}
            limits: {cpu: 200m, memory: 128Mi}
      volumes:
        - name: config
          configMap: {name: mosquitto-config}
    

